### ISSUE TITLE
Auditing checklist

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#107]
Feel free to put things here @kaichaosun @yz89

**Comment by kaichaosun** [comment]
A few points:
- AccountCollateralBalance not needed, can be merge in AccoutCollatoral
- check if keeplive needed when transfer using orml currencies
- collateral asset internal  function has nested if else
- check whether shortfall logic is needed when liquidation
- remove unnecessary internal functions, put the code in dispatchables directly.

**Comment by GopherJ** [comment]
- [ ] check whether shortfall logic is needed when liquidation @kaichaosun 

- [ ] remove unnecessary internal functions, put the code in dispatchables directly. @GopherJ 
- [ ] collateral asset internal function has nested if else @GopherJ 
- [ ] check if keeplive needed when transfer using orml currencies @GopherJ 

- [ ] AccountCollateralBalance not needed, can be merge in AccoutCollatoral @yz89

**Comment by GopherJ** [comment]
we also need to have benchmarks of common pallets, eg. https://github.com/paritytech/statemint/blob/master/scripts/benchmarks.sh

**Comment by GopherJ** [comment]
@kaichaosun regarding:

> check if keeplive needed when transfer using orml currencies

I didn't find any related doc/api of orml_currencies

**Comment by GopherJ** [comment]
https://github.com/open-web3-stack/open-runtime-module-library/blob/master/currencies/src/lib.rs#L565

looks like if we transfer native token, it allows death of account

**Comment by GopherJ** [comment]
close this as most of items are solved
