### ISSUE TITLE
AMM & Router pallet production ready checklist

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1191]
- [ ] https://github.com/parallel-finance/parallel/issues/1190 @ashi20192020ayush  (**high priority**)
- [x] https://github.com/parallel-finance/parallel/issues/1188 @ashi20192020ayush 
- [x] https://github.com/parallel-finance/parallel/issues/1186 @c02fee 
- [x] https://github.com/parallel-finance/parallel/issues/1187 @c02fee 
- [ ] https://github.com/parallel-finance/parallel/issues/1169 @rustaceanstayhigh  (**high priority**)
- [x] https://github.com/parallel-finance/parallel/issues/1181 @drbh 
- [x] https://github.com/parallel-finance/parallel/issues/1180 @drbh 
- [x] https://github.com/parallel-finance/parallel/issues/1176 @ashi20192020ayush  (**high priority**)
- [x] https://github.com/parallel-finance/parallel/issues/1175 @ashi20192020ayush 
- [x] https://github.com/parallel-finance/parallel/issues/1167 @ashi20192020ayush 
- [ ] https://github.com/parallel-finance/parallel/issues/1163 @drbh  (**high priority**)
- [x] https://github.com/parallel-finance/parallel/issues/1164 @drbh 
- [x] https://github.com/parallel-finance/parallel/issues/1196 @drbh @ashi20192020ayush 
- [ ] https://github.com/parallel-finance/parallel/issues/1182

**Comment by GopherJ** [comment]
- [ ] AMM code cleanup & refactorings #1167 @ashi20192020ayush
  - [ ] Enrich AMM pallet's events with amount #1186 @c02fee
  - [ ] Use compact amount in amm pallet #1187 @c02fee
  - [ ] Remove expiry parameter from AMM router #1181 @drbh
  - [ ] Rename stuff like `ownership`.. to make things more clar
  - [ ] Add small functions
  - [ ] Export interfaces like uniswap v2 Library, and give it to router
  - [ ] No need to record amm liquidity provider's position #1175 @ashi20192020ayush
- [ ] AMM protocol fees should be paid using lp tokens #1176 @ashi20192020ayush (high priority)
- [ ] Use FixedU128 for AMM's reserve0, reserve1 so that k will not overflow due to big decimals #1190 @ashi20192020ayush (high priority)
- [ ] TWAP based oracle in AMM #1163 @drbh (high priority)
- [ ] AMM rpc for smart router #1169 @rustaceanstayhigh (high priority)
- [ ] AMM implement swapExactTokensForTokens, swapTokensForExactTokens #1180 @drbh
- [ ] AMM pool will be deleted accidently after one trade/removeLiquidity #1188 @ashi20192020ayush
- [ ] AMM locked minimum liquidity #1164 @drbh
- [ ] Liquidity mining improvement checklist #1196 @drbh @ashi20192020ayush
- [ ] Support custom formula in AMM #1182

**Comment by GopherJ** [comment]
auditing will happen mid february

**Comment by drbh** [comment]
** auditing will likely start on February 5th

**Comment by GopherJ** [comment]
close as nearly finished
