### ISSUE TITLE
Liquidity mining improvement checklist

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1196]
- [ ] replace `take` by `as_mut` to make it more efficient
- [ ] rename WithdrewAssets -> AssetsWithdrew, rename DepositedAssets -> AssetsDeposited to make naming rule consistent
- [ ] use into_sub_account_id to simplify `pool_account_id` function 
- [ ] use compact balance in deposit & withdraw
- [ ] add liquidity mining to heiko & parallel runtime but disable them in baseFilter & make it possible to emergency shutdown it
- [ ] how can we renew liquidity mining program in a different period? like for HKO with LM-HKO as shares token, how can we do the same liquidity mining for block 1 -> 100 then block 200 -> 300 ? or do we prefer maybe a new shares token?
- [ ] rename `shares` and `asset` to make it more meaningful
- [ ] rename `balance` in rewards bounded vec to `perBlock` to make it more meaningful

**Comment by ashi20192020ayush** [comment]
@GopherJ Few questions:

1) Regarding `use into_sub_account_id to simplify pool_account_id function`: Do you mean rename function `pool_account_id`?

2) I didn't get last point ` rename balance in rewards bounded vec to perBlock to make it more meaningful`. Could you please explain a bit?
