### ISSUE TITLE
liquid staking production ready checklist

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1298]
- [x] #1291 (low priority)
- [x] #1294 
- [x] #1295 
- [x] #1296 
- [ ] #1297 (low priority)
- [x] #1237 (hight priority) @GopherJ  @MrPai 
- [x] #1238 (low priority)
- [x] #856 
- [ ] #1299 
- [x] #1300 (low priority)
- [x] #1301 (high priority) @MrPai 
- [x] #1303 (high priority) @GopherJ 
- [x] #1313 
- [x] #1314 
- [x] #1334
- [x] #1335 
- [x] #1336
- [x] https://github.com/parallel-finance/parallel/issues/1233 @ashi20192020ayush 
- [x] #1343 
- [x] #1344 
- [x] #1345 
- [x] #1346
- [x] #1355
- [x] #1340
- [ ] #1332
- [ ] #1302 
- [x] #1329 
- [x] #1366 
- [x] #1404 
- [x] #1426 
- [x] #1427 
- [x] #1428
- [ ] #1429
- [ ] #1430 
- [ ] #1431 
- [x] #1444 
- [x] #1442 
- [x] #1445 
- [x] #1455

**Comment by GopherJ** [comment]
close as nearly finished
