### ISSUE TITLE
Add Insurance to staking pool

### ISSUE THREAD

**Issue by yubo-ruan** [parallel-finance/parallel#150]
**Motivation**

Currently, over 50% of DOT/KSM has been staked however there is no solution to purchase a staking insurance. Investors and stakers are looking for an alternative to protect to their staking assets. 

**Suggested Solution**

I propose to add an insurance mechanism for xKSM staking pool. Our system will charge a small fee, such as 0.05% of staked amount and direct them into a insurance fund and share with PARA token holder. Similar to MakerDAO, whenever an indisputable slash to our staking pool, we will sell PARA token through a public auction to make up the losses within 48 hours. 

**Benefits**

With the proposed insurance protection, investors are able to protect again potential slashes and thus, Parallel staking pool will increase in size due to the confidence we bring to the market. 

On the other hand, Parallel don't have to worry about the liquidation on xKSM to KSM pair. We can avoid the necessary liquidation and make the system much more stabilized and robust. It also provides a better price discovery mechanism for xKSM without worrying about liquidity in the AMM pool. 

**TODO (tentative) **

- [ ] Add insurance protection from PARA auction against slashes from the staking pool
- [ ] Disable xKSM/KSM liquidation
- [ ] or update exchange = (staking pool balance + PARA token insurance) / xKSM total supply

**Alternatives**

No alternative live on the market yet.
