### ISSUE TITLE
Liquid staking v3 checklist

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1503]
- [x] #1471 (HIGH)
- [ ] #1331 (HIGH)
- [x] #1328 (HIGH)
- [ ] #1302 (HIGH)
- [x] #1506 (MEDIUM)
- [x] #1509 (MEDIUM)
- [ ] #1507
- [ ] #1508
- [x] #1510 (HIGH)
- [ ] #1511 (HIGH)
- [ ] #1512
- [ ] #1514 (MEDIUM)
- [ ] LS UI updates
- [ ] LS Analytics
- [ ] Add probably force_claim_for, force_remove_xcm_request
- [ ] #1524
- [ ] #1525
- [ ] being able to set controller to validator provider
- [x] lockable matching pool
- [x] set_staking_ledger should only be able to feed rewards nothing else even slashes

**Comment by GopherJ** [comment]
## Analytics

![image](https://user-images.githubusercontent.com/33961674/159128471-99d0e5fe-14fc-4baa-8842-5207afd08572.png)

**Comment by GopherJ** [comment]
## UI

- [ ] optimize mobile display
<img width="447" alt="image" src="https://user-images.githubusercontent.com/33961674/159156033-d6f081aa-f5c6-4e79-aaf3-e697a0f04927.png">
- [ ] replace `Staking Balance`
