### ISSUE TITLE
Asset manager release checklist

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#1578]
- [x] Make name consistent, we are using AssetRegistrar as trait name, will be good to use asset-registrar for pallet name to make it consistent
- [x] mv hard coded pallet id to runtime as a pallet config
- [x] mv AssetRegistrar trait to primitives/src/xcm.rs
- [x] rename primitives/src/xcm_gadget.rs to primitives/src/xcm.rs
- [ ] simplify migration code to insert only units per second & asset id <-> multilocation mapping
- [x] register_asset make metadata mandatory
- [ ] version management of multilocation passed in parameters

**Comment by yrong** [comment]
The new pallet should work side by side with the legacy foreign assets, so  I would suggest we keep this pr focused and move that to future pr.

**Comment by yrong** [comment]
Since without the `VersionedMultilocation` we can still fulfill the future migration, and the register call is usually not used directly by frontend, so we keep it simple here just use `Multilocation`
