### ISSUE TITLE
Parallel v194 Release checklist

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#1902]
# Release Checklist
This release checklist is for Parallel v194, includes Parallel/Heiko/Kerria/Vanilla

## Runtime Release
these checks include runtime-related updates, on-chain logic
- [x] #1899 
- [x] enable more assets gov call
   - #1898 
   - #1906
- [x] #1891
- [x] #1900
- [x] #1901
- [x] #1904
- [x] #1911

## All Release
these checks include the update about node, ci and helper scripts
- [x] CI check: TryRuntimeUpgrade & ExtrinsicOrdering
   - https://github.com/parallel-finance/parallel/actions/runs/3598594238
   - https://github.com/parallel-finance/parallel/actions/runs/3599268145
   - https://github.com/parallel-finance/parallel/actions/runs/3599269598
- [x] Update Frontend
    - https://github.com/parallel-finance/parallel-dapp/issues/2051
- [x] Test through FE (include Transfer/AMM/Staking/MM, all function)
    - #1908
- [x] #1905 
- [x] Update parallel.js
    - https://github.com/parallel-finance/parallel-js/pull/64
- [x] Test parachain xcm transfer

**Comment by MrPai** [comment]
## heiko
https://parallel-heiko.subscan.io/referenda/11
