### ISSUE TITLE
Parallel v195 Release checklist

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#1917]
# Release Checklist
This release checklist is for Parallel v195, includes Parallel/Heiko/Kerria/Vanilla

## Runtime Release
these checks include runtime-related updates, on-chain logic
- [x] remove member check, only use merkle-proof #1915
- [x] integrate evm into heiko and parallel #1916

## All Release
these checks include the update about node, ci and helper scripts
- [x] CI check: TryRuntimeUpgrade & ExtrinsicOrdering
  - https://github.com/parallel-finance/parallel/actions/runs/4220052776
  - https://github.com/parallel-finance/parallel/actions/runs/4220099695
- [x] Test through FE (include Transfer/AMM/Staking/MM, all function)
- [x] Update parallel.js
  - https://github.com/parallel-finance/parallel-js/pull/65
- [x] Test EVM function

**Comment by MrPai** [comment]
Heiko
https://parallel-heiko.subscan.io/council/323
