### ISSUE TITLE
Parallel v196 Release checklist

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#1921]
# Release Checklist
This release checklist is for Parallel v195, includes Parallel/Heiko/Kerria/Vanilla

## Runtime Release
these checks include runtime-related updates, on-chain logic
- [x] bump to 0.9.36 #1919 
- [x] evm data migration, register precompile code #1923
- [x] benchmark weight #1927 

## All Release
these checks include the update about node, ci and helper scripts
- [x] CI check: TryRuntimeUpgrade & ExtrinsicOrdering
   - https://github.com/parallel-finance/parallel/actions/runs/4522165582
   - https://github.com/parallel-finance/parallel/actions/runs/4522164161
- [x] Test through FE (include Transfer/AMM/Staking/MM, all function)
- [x] Update parallel.js https://github.com/parallel-finance/parallel-js/pull/66
- [x] Test EVM data migration, try-runtime #1922 
- [x] update oracle-client and verify https://github.com/parallel-finance/oracle-client/pull/68

**Comment by MrPai** [comment]
Heiko runtime upgrade proposal
- [ ] 1

Parallel runtime upgrade proposal
- [ ] 1
