### ISSUE TITLE
Parallel v198 Release checklist

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#1937]
# Release Checklist
This release checklist is for Parallel v195, includes Parallel/Heiko/Kerria/Vanilla

## Runtime Release
these checks include runtime-related updates, on-chain logic
- [x] #1936
- [x] #1938
- [ ] update the Xcm fee and weight in 'XcmHelper' pallet.
   - [x] update in heiko: https://parallel-heiko.subscan.io/council/424
   - [ ] update in parallel （no need）

## All Release
these checks include the update about node, ci and helper scripts

**Comment by MrPai** [comment]
## heiko
- [ ] https://parallel-heiko.subscan.io/council/425
## parallel
- [ ] x
