### ISSUE TITLE
money market launch checklist

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#260]
## Priorities

> Bug Fixes > Safety Check > Features  > Enhancement > Governance > CI/CD >= Deployment > Learnings & Practices > Benchmark

## Features

- [ ] Emergency shutdown market https://github.com/parallel-finance/parallel/issues/188
- [x] Liquidation Client Release (docs, npm package, support custom keystore, support list underwater accounts)
- [x] Oracle emergency price feed mode https://github.com/parallel-finance/oracle-client/issues/35
- [x] Oracle more data source https://github.com/parallel-finance/oracle-client/issues/12
- [x] Oracle alerts & monitoring (pagerduty doesn't work yet) https://github.com/parallel-finance/oracle-client/issues/31
- [x] #655
- [ ] #656
- [x] #658 

## Enhancement

- [ ] Research on market's initial configuration (eg. collateral_factor)

## Governance

- [ ] Council/Technical Commitee Members

## Deployment

- [ ] API services bootnodes, hosted by parallel/onfinality
- [ ] Oracle distributed & confidential deployment https://github.com/parallel-finance/oracle-client/issues/13

## Safety Check

- [ ] Total borrow & accout borrow accure interests in a different way https://github.com/parallel-finance/parallel/issues/59

## Learnings & Practices

- [ ] Governance practices
- [ ] Runtime upgrade practices #625 

## Benchmark

- [x] Fix loans benchmarks #545

**Comment by yubo-ruan** [comment]
I put some tasks on Marketing and Fundraising
