### ISSUE TITLE
Tasks overview to make code in node production ready

### ISSUE THREAD

**Issue by kaichaosun** [parallel-finance/parallel#30]
## Tasks

Tasks to make the code production ready.

### loans

- [ ] test coverage for dispatchables
    - [x] mint
    - [x] redeem
    - [x] redeem_all
    - [x] borrow
    - [x] repay_borrow
    - [x] repay_borrow_all
    - [ ] transfer_token
    - [x] collateral_asset
    - [x] liquidate_borrow
- [ ] refactor code, mainly storages and dispatchables
    - [x] comments/rustdocs for all errors/events, dispatchables, storages
    - [ ] minimum storage usage, bounded execution/storage, short function
    - [ ] add traits for pallet to abstract the behaviour
    - [x] move the main pallet implementation in [lib.rs](http://lib.rs/)
    - [ ] extract to new pallets if storages/dispatchables can be separated
    - [x] exchange_rate to use [fixed point number](https://substrate.dev/recipes/fixed-point.html), rational of precision
    - [x] `pub mod module` change to `pallet`, put `impl Pallet` out of this module
- [ ] xcm-token transfer
- [ ] benchmark for dispatchables in this module
- [x] license

### liquidate:

- [ ] test coverage for `execute_liquidation`
- [x] short `liquidate` function by extracting a few small functions
- [x] remove `outer` loop if possible
- [ ] randomly run offchain liquidation to give general user chance to process liquidation
- [x] comments
- [ ] benchmark
- [x] license

### ocw price feed:

- [x] research if api key is needed to get more quota or more stable service (rpc offchain_localStorageSet)
- [x] use StorageLock to make api call not exceed the threshold
- [x] bound the onchain data by limit the size of price set or the node can send price

### staking

- [ ] document the workflow with staking's dispatchables about validation or nomination
- [ ] abstract the nomination workflow in parallel with traits given above docs
- [ ] offchain nomination with a multisig account in relaychain
- [ ] xcm nomination

**Comment by yz89** [comment]
I think we can close this issue now.
