### ISSUE TITLE
Money Market - Missing components

### ISSUE THREAD

**Issue by Helen8** [parallel-finance/parallel#369]
These are currently not started - we can break these up into separate cards after discussion on estimates for development:

- [x] Add liquidation client - 0% => need to release a version
- [x] Need emergency shut down feature - 0% #188 
- [ ] Ability to delete market - 0%
- [x] Addition of pToken - 0% #334 
- [x] Create testing framework (function, performance, edge case) - 0%
- [ ] Enable liquidity mining feature - 0%
- [x] Fix add_market - 0% #423
