### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#442]
- [x]  prepare polkadot apps PR *
- [x] bump to polkadot-v0.9.9 *
- [x] prepare live chainspec *
- [x] prepare final wasm (activate base call filter, check governance settings) *
- [x] runtime upgrade test *
- [x] auctions, crowdloan test *
- [ ] #492
- [x] rococo, westend test *
- [ ] test collator selection
- [ ] #491
- [x] collator launch script

**Comment by GopherJ** [comment]
https://github.com/parallel-finance/parallel/pull/438 bump polkadot to v0.9.9 and tested working

**Comment by GopherJ** [comment]
https://github.com/parallel-finance/parallel/pull/443 added the final wasm, need to test

**Comment by GopherJ** [comment]
bootnode should look like:

```
/dns/heiko-bootnode-0.parallel.fi/tcp/30333/...
```
