### ISSUE TITLE
Upgrade LiquidStaking with XCM transact checklist

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#502]
**Motivation**

Since XCM transact works well, for now, we may consider a more decentralized solution about LiquidStaking.

Here is the main checklist that provides an overview of what should be included in it. It will be necessary that we could build more detailed issues tracking each task.

**Related issues**
research and test about `xcm/transact`, integrate with `xcm-simulator` #440
encode/decode bug about `staking.bond` #489 

**Suggested Solution**
- [x] integrate xcm-simulator #377
***
- [ ] xcm transct, derivative account: `utility.as_derivative` and unit test #527
***
- [ ] xcm transfer: `balance.transfer` and unit test #548
***
- [x] xcm transct: `staking.bond` method and unit test #528
- [x] xcm transct: `staking.bond_extra` method and unit test #528
- [x] xcm transct: `staking.unbond` method and unit test #533
- [x] xcm transct: `staking.rebond` method and unit test #533
- [x] xcm transct: `staking.nominator` method and unit test #552 
- [x] xcm transct: `staking.payoutStakers` method and unit test #552 
- [x] xcm transct: `staking.withdraw_unbond` method and unit test #533

**Comment by GopherJ** [comment]
maybe we can do: #377  first so that we can run tests
