### ISSUE TITLE
Test Liquidstaking in Polkadot UI

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#706]
## Test function list
- [x] liquidstaking.stake
- [x] liquidstaking.unstake
- [x] liquidstaking.record_staking_settlement
- [x] liquidstaking.force_update_xcm_fees_compensation
- [x] liquidstaking.settlement
- [x] liquidstaking.bond
- [x] liquidstaking.bond_extra
- [x] liquidstaking.unbond
- [x] liquidstaking.rebond
- [x] liquidstaking.withdraw_unbonded
- [x] liquidstaking.nominate
- [x] liquidstaking.payout_stakers (need to remove this method)
- [x] liquidstaking.set_liquid_currency
- [x] liquidstaking.set_staking_currency

## Bug list
- [x] when already bond on relaychain, and then the second time invoke `settlement` on relaychain, if the `bonding_amount` is not zero(by mistake), then will dispatch a `bond` call, it will fail on relaychain. #723
        **suggest**: change `bonding_amount` to `bool`
- [x] xcm payout_stakers bug, https://github.com/parallel-finance/parallel/issues/706#issuecomment-944846073 #723
- [x] record_staking_settlement, `MaxRewardsPerEra` and `MaxSlashesPerEra` is too low, https://github.com/parallel-finance/parallel/issues/706#issuecomment-944854226 #723

## Refer
ParaId **2085** account id: 
`5Ec4AhNtg8ug9xAezbpQom1Pz4PtM7q9bF12AC4T6Zp1PoCB`
**2085_0** account id( is the derivated account of 2085 in index 0): 
`5EAmv9oydjn3BkFJEaeB6X59S2TUsLFfZKLbepsLkdeCBset`

**Comment by MrPai** [comment]
### payout_stakers bug
send from parachain
![payoutStakers](https://user-images.githubusercontent.com/26266313/137571522-50de4399-27a6-46f2-9187-c4aefaad3f4c.jpg)
bug on relaychain
![payeroutstakers bug](https://user-images.githubusercontent.com/26266313/137571525-fffb3eba-c16a-4ed2-bcb8-4df40afcb906.jpg)
