### ISSUE TITLE
initialization operation checklist when launch liquidstaking

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#721]
- [x] initial `StakingPoolCapacity` an appropriate value
- [x] initial `XcmFeesCompensation` an appropriate value
- [x] initial `XcmWeightMisc` an appropriate value

**Comment by GopherJ** [comment]
done
