### ISSUE TITLE
Liquid staking refactor checklist

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#844]
- [ ] (low) #787  blocked by polkadot 
- [x] (low) remove liquidCurrency & stakingCurrency storage as it's not necessary, consider using runtime config
- [x] (high) #741 
- [x] (low) #769 
- [x] (high) #919
- [ ] ~refactor MaxRewardsPerEra to use Permil & max inflation, how about max slashes? what's the reasonable value~
- [x] (high) #924
- [x] avoid reaping pallet id?
- [x] (low) #570 (self build validator node)
- [ ] (middle) No reserves, no platform earnings => reserves mixed with xcm fees, (need to clarify these concept and design)
- [x] (high) on_idle may not execute because it consumes too much weights at one time
- [ ] (middle) hard to reuse refunded xcm fees, xcm fee deposit to a special account, goverance this account. #937
- [x] Fix stake client -> governance + withdraw_unbonded
- [ ] (middle) queue priority (big unstake amount, on_idle didn't execute yet, then another guy unstake 10, then this person still needs to be blocked)
- [ ] (low) update gitbook document
- [x] (high) benchmark test on_idle #930 . @MrPai 
- [ ] (low) minimum stake. and unstake, improve UX
- [x] #1017 
- [x] #1018 
- [x] #1019
