### ISSUE TITLE
parallel auction checklist

### ISSUE THREAD

**Issue by GopherJ** [parallel-finance/parallel#853]
- [x] prepare polkadot apps UI. color, logo, spec, endpoints @GopherJ 
- [ ] prepare bootnodes @GopherJ @woshihahaha 
- [x] prepare onfinality spec @GopherJ 
- [x] prepare rpc nodes @GopherJ 
- [x] test producing blocks after winning auction @GopherJ @yz89 
- [ ] test producing blocks on westend @GopherJ  @yz89 
- [x] #852 @yz89 
- [x] prepare final chainspec & wasm @GopherJ 
- [x] reserve para id @yubo-ruan 
- [ ] test runtime upgrade to open calls @GopherJ  @yz89 @yubo-ruan 
- [x] submit final genesis & wasm @yubo-ruan
